site_name: BudgetPlan Docs
# extra_css: [style.css]
repo_url: https://github.com/heuvel/budgetplan
site_url: https://heuvel.github.io/budgetplan/
site_description: Python package to plan your future budget, playing around interactively using what-if scenarios
site_author: Arjan vd Heuvel
use_directory_urls: false
nav:
  - Home: index.md
  - API:
      - Assets: api/assets.md
plugins:
  - mkdocstrings:
      watch:
        - budgetplan
  - search
copyright: Copyright &copy; 2021 Maintained by Arjan.
theme:
  name: material
  # custom_dir: theme/
  # icon:
    # logo: material/library
  font:
    text: Ubuntu
    code: Ubuntu Mono
  # favicon: logo.png
  # logo: logo-white.png
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: blue
markdown_extensions:
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true
